import type { QuestionInsightData } from "./types";

export const questionInsightCatalog: QuestionInsightData[] = [
  {
    id: "home-work",
    context: "home",
    prompt: "我现在更适合换方向，还是先把手上的事做好？",
    shortLabel: "要不要换方向",
    source: "来自生辰结构与当前阶段节奏，仅供自我观察",
    interpretation: "你并不是不能改变，而是需要先确认改变能带来什么积累。比起立刻离开，现在更适合把新方向缩小成一次可验证的尝试。",
    observation: "如果你最近反复搜索新机会，却很少完成手上的关键任务，疲惫可能来自失去完成感，而不一定是方向本身错误。",
    action: "保留主线，用一周时间完成一个低成本的新方向测试。",
    tone: "ink",
  },
  {
    id: "home-relationship",
    context: "home",
    prompt: "这段关系值得我继续投入吗？",
    shortLabel: "关系值不值得",
    source: "来自关系倾向与互动习惯，仅供自我观察",
    interpretation: "你需要的不只是热度，而是稳定、清楚、可以被验证的回应。判断一段关系时，持续行动比偶尔的热烈更有参考价值。",
    observation: "当回应含糊时，你容易把精力用在猜测上，并不断降低自己的真实需求。",
    action: "提出一个具体需求，再观察对方是否愿意稳定回应。",
    tone: "coral",
  },
  {
    id: "home-action",
    context: "home",
    prompt: "最近我应该主动一点，还是先观察？",
    shortLabel: "主动还是观察",
    source: "来自行动方式与阶段节奏，仅供自我观察",
    interpretation: "更适合先主动一次，再根据真实反馈决定是否继续。这样既不会错过机会，也不用靠连续加速证明自己。",
    observation: "你真正需要的不是等待完美时机，而是一个足够小、可以撤回的第一步。",
    action: "今天只做一次清楚表达，然后给结果留出观察时间。",
    tone: "sage",
  },
  {
    id: "home-energy",
    context: "home",
    prompt: "为什么最近总觉得很累？",
    shortLabel: "为什么总觉得累",
    source: "来自环境适配与精力使用习惯，仅供自我观察",
    interpretation: "真正消耗你的，可能不是事情多，而是标准反复、反馈不清和频繁切换。你需要先减少不确定，再谈提高效率。",
    observation: "一天结束时，如果你做了很多回应却说不出完成了什么，精力通常会明显下降。",
    action: "暂停一项低回报回应，把精力留给一个可以完成的结果。",
    tone: "warm",
  },
  {
    id: "home-choice",
    context: "home",
    prompt: "面对两个选择，我该先看什么？",
    shortLabel: "两个选择怎么选",
    source: "来自决策习惯与稳定需求，仅供自我观察",
    interpretation: "你更适合先比较长期积累、边界清晰度和可复盘程度，而不是只比较眼前的新鲜感。",
    observation: "越是害怕错过，你越容易忽略真正会长期承担的成本。",
    action: "分别写下两个选择在三个月后会留下什么，再做判断。",
    tone: "violet",
  },
  {
    id: "home-today",
    context: "home",
    prompt: "今天最值得我先做的一件事是什么？",
    shortLabel: "今天先做什么",
    source: "来自今日提醒与惯用行动方式，仅供自我观察",
    interpretation: "今天最值得先做的，是一件边界清楚、完成后能减少后续反复的小事。它不一定最显眼，但会让你重新找回掌控感。",
    observation: "当一个未完成事项不断占用注意力时，新任务也很难真正开始。",
    action: "选出一个 30 分钟内可以完成并交付的动作，现在开始。",
    tone: "sky",
  },
  {
    id: "bazi-environment",
    context: "bazi",
    prompt: "什么样的环境更容易让我发挥？",
    shortLabel: "环境怎么选",
    source: "来自五行重心与工作适配，仅供自我观察",
    interpretation: "规则清楚、反馈及时、允许形成方法的环境更容易让你稳定发挥。你不怕难，真正消耗你的是标准反复变化。",
    observation: "目标明确时你会越做越快；责任含糊时，你会把大量精力用在确认和防守上。",
    action: "进入新环境前，先问清目标、责任和反馈周期。",
    tone: "ink",
  },
  {
    id: "bazi-relationship",
    context: "bazi",
    prompt: "我在关系里最在意什么？",
    shortLabel: "关系里在意什么",
    source: "来自生辰关系倾向，仅供自我观察",
    interpretation: "你最在意的是言行一致和稳定回应。热烈会吸引你，但真正让你留下的是不用反复猜测。",
    observation: "当安全感不足时，你容易先检查对方有没有做到，而忘记说出自己的真实感受。",
    action: "先说需求，再讨论谁对谁错。",
    tone: "coral",
  },
  {
    id: "bazi-pace",
    context: "bazi",
    prompt: "现在更适合主动，还是稳住？",
    shortLabel: "主动还是稳住",
    source: "来自阶段趋势与行动结构，仅供自我观察",
    interpretation: "先稳住长期主线，再挑一件真正值得的事主动。全面加速会分散积累，完全等待也会错过反馈。",
    observation: "只要第一步足够小，你不需要等到完全确定才行动。",
    action: "保留主线，给新机会一次有限投入。",
    tone: "sage",
  },
  {
    id: "bazi-drain",
    context: "bazi",
    prompt: "什么事情最容易消耗我？",
    shortLabel: "什么最消耗我",
    source: "来自五行结构与压力反应，仅供自我观察",
    interpretation: "反复变化的标准、含糊的责任和没有结果的沟通最容易消耗你。问题不是你不够灵活，而是长期缺少确定反馈。",
    observation: "越想把所有变量都控制住，你越容易把精力耗在无法决定的部分。",
    action: "划出一件你能控制的事和一件暂时放下的事。",
    tone: "warm",
  },
  {
    id: "zodiac-attraction",
    context: "zodiac",
    prompt: "我会喜欢什么样的人？",
    shortLabel: "会喜欢谁",
    source: "来自太阳、金星与上升配置，仅供自我观察",
    interpretation: "有趣和直接会让你靠近，稳定行动会让你留下。只有话题却没有兑现的人，很难长期打动你。",
    observation: "你可能先被交流的火花吸引，后来才发现自己更在意对方是否可靠。",
    action: "除了聊天感觉，也观察对方是否愿意落实一个小约定。",
    tone: "coral",
  },
  {
    id: "zodiac-fear",
    context: "zodiac",
    prompt: "我在关系里最害怕什么？",
    shortLabel: "关系里怕什么",
    source: "来自月亮与上升配置，仅供自我观察",
    interpretation: "你最怕的不是争执，而是对方忽然失去回应，让你不知道关系处在哪里。明确比表面和平更能带来安全感。",
    observation: "当回应消失时，你可能会在主动追问和突然撤退之间摇摆。",
    action: "先确认关系事实，不用靠冷淡保护自己。",
    tone: "violet",
  },
  {
    id: "zodiac-hot-cold",
    context: "zodiac",
    prompt: "我为什么有时会忽冷忽热？",
    shortLabel: "为何忽冷忽热",
    source: "来自太阳双子与月亮白羊的反应差异，仅供自我观察",
    interpretation: "你既需要新鲜回应，也需要快速确认感受。输入太少时会觉得无聊，情绪太满时又会想先退开。",
    observation: "忽冷忽热往往不是不在意，而是你还没找到既能表达又不被淹没的节奏。",
    action: "想退开时先说明需要一点时间，并约定何时继续沟通。",
    tone: "sky",
  },
  {
    id: "zodiac-relax",
    context: "zodiac",
    prompt: "什么样的人会让我真正放松？",
    shortLabel: "谁让我放松",
    source: "来自上升金牛与月亮需求，仅供自我观察",
    interpretation: "稳定、坦率、不强迫你持续表现的人更容易让你放松。你需要有话可说，也需要允许安静相处。",
    observation: "真正舒服的关系不会要求你一直有趣，也不会把短暂安静解释成疏远。",
    action: "留意谁能接住你的沉默，而不急着索取回应。",
    tone: "sage",
  },
  {
    id: "zodiac-initiative",
    context: "zodiac",
    prompt: "感情里我更适合主动，还是被动？",
    shortLabel: "主动还是被动",
    source: "来自金星、火星与月亮配置，仅供自我观察",
    interpretation: "你适合清楚地主动一次，然后根据回应决定下一步。持续追逐会消耗你，完全被动又容易错过真正想要的人。",
    observation: "主动的价值是获得真实信息，不是保证关系一定发生。",
    action: "表达一次具体邀请，把下一步交给双方回应。",
    tone: "warm",
  },
];

export function getQuestions(context: QuestionInsightData["context"]) {
  return questionInsightCatalog.filter((item) => item.context === context);
}

export function getQuestion(id: string) {
  return questionInsightCatalog.find((item) => item.id === id) ?? questionInsightCatalog[0];
}
