// ── FACT data: comes from user input, deterministic ──────────────────────────
export type RelationType =
  | 'lover' | 'partner' | 'ambiguous' | 'friend' | 'family' | 'colleague' | 'other';
export type ChartType = 'synastry' | 'birth';
export type NavTab = 'home' | 'report' | 'tools' | 'my';
export type AppScreen =
  | 'home' | 'create-1' | 'create-2' | 'generating' | 'result'
  | 'history' | 'tools' | 'profile';

export interface PersonFact {
  id: string;
  name: string;
  birthday: string;         // YYYY-MM-DD — required for synastry
  birthTime: string;        // HH:MM or '' if unknown
  birthTimeAccuracy: 'exact' | 'approximate' | 'unknown';
  birthPlace: string;
  avatarColor: string;      // hsl/hex
  avatarChar?: string;      // defaults to name[0]
}

// ── API content: generated by DeepSeek per (person1, person2, relationType) ──
export interface ReportSection {
  key: string;
  title: string;
  colorKey: SectionColorKey; // maps to design token, not hardcoded color
  score?: number;
  body: string;              // API-injected
  signals?: string[];        // API-injected
  actions?: string[];        // API-injected
}

export type SectionColorKey =
  | 'lavender' | 'coral' | 'sky' | 'mint' | 'gold' | 'ink';

export interface ReportApi {
  heroTitle: string;
  heroSubtitle: string;
  summary: string;
  tags: string[];
  overallScore: number;
  scores: {
    attraction: number;
    emotion: number;
    communication: number;
    values: number;
    pace: number;
    intimacy: number;
  };
  sections: ReportSection[];
  todayStep: string;
  questions: string[];
}

// ── Merged record: stored after generation ───────────────────────────────────
export interface SynastryRecord {
  id: string;
  // FACT fields
  person1: PersonFact;
  person2: PersonFact;
  relationshipType: RelationType;
  chartType: ChartType;
  createdAt: string;
  // API fields (from ReportApi)
  api: ReportApi;
}

// ── Create flow state ─────────────────────────────────────────────────────────
export interface CreateFlowData {
  person2: Partial<PersonFact>;
  relationshipType?: RelationType;
  chartType: ChartType;
}

// ── Display helpers ───────────────────────────────────────────────────────────
export const RELATION_LABELS: Record<RelationType, string> = {
  lover: '恋人', partner: '伴侣', ambiguous: '暧昧',
  friend: '朋友', family: '家人', colleague: '同事', other: '其他',
};

// Kept for backwards-compatibility with any cached module references
export const RELATION_EMOJIS: Record<RelationType, string> = {
  lover: '♡', partner: '◎', ambiguous: '◑', friend: '◇',
  family: '△', colleague: '□', other: '○',
};

export const SECTION_COLORS: Record<SectionColorKey, { bg: string; text: string; border: string }> = {
  lavender: { bg: '#EDE8F8', text: '#7B65C4', border: 'rgba(196,181,232,0.5)' },
  coral:    { bg: '#FDEAE5', text: '#C85840', border: 'rgba(240,169,154,0.5)' },
  sky:      { bg: '#E0F0FA', text: '#3E8FB0', border: 'rgba(133,195,232,0.5)' },
  mint:     { bg: '#D8F4EB', text: '#3A9678', border: 'rgba(160,217,196,0.5)' },
  gold:     { bg: '#F5E8C0', text: '#A07820', border: 'rgba(212,168,71,0.5)' },
  ink:      { bg: '#F0EEF5', text: '#4A4268', border: 'rgba(150,130,200,0.3)' },
};
